import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Log Anomaly Detector",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* --- NEW NAVIGATION BAR --- */}
        <header className="bg-white dark:bg-gray-800 shadow-sm">
          <nav className="container mx-auto px-4 sm:px-8 py-4 flex items-center space-x-8">
            <Link href="/" className="text-lg font-semibold text-gray-700 dark:text-gray-200 hover:text-blue-600">
              Dashboard
            </Link>
            <Link href="/anomalies" className="text-lg font-semibold text-gray-700 dark:text-gray-200 hover:text-blue-600">
              Anomalies
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
